# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: (docs|.*\..*lock$|\.vscode|\.phan|^acceptance-test-results\.md$|^LICENSE$)
    -   id: end-of-file-fixer
        exclude: (docs|.*\..*lock$|\.vscode|\.phan|^acceptance-test-results\.md$|^LICENSE$)
    -   id: check-json
        exclude: .*\..*lock$
    -   id: check-xml
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: .*\..*lock$
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
    -   id: commitizen
-   repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
    - id: php-lint
    - id: php-cs
      files: \.(php)$
      exclude: (examples)
      args: ["--standard=PSR1,PSR12,./phpcs.xml", "-p"]
    - id: php-unit
    - id: php-stan
      files: \.(php)$
      exclude: (examples|test)
-   repo: https://gitlab.com/daverona/pre-commit/php
    rev: 0.6.0          # use the most recent version
    hooks:
    # Hooks using native
    - id: phpmd         # static analyzer for PHP code
      exclude: (examples|test)
