name: Prod Upgrade Release
on:
  schedule:
    # every Sunday at 9:15PM UTC
    - cron: '15 9 * * 0'
permissions:
  contents: write
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
